### ISSUE TITLE
Document extensions to jquery.payment

### ISSUE THREAD

**Issue by cancan101** [jondavidjohn/payform#15]
Add to readme notes on what is added by this issuance vs jquery.payment.

**Comment by jondavidjohn** [comment]
While this is a derived work from jquery.payment, I am not proposing it is a drop in replacement and/or should maintain compatibility, it is possible (though not likely) they could diverge significantly.  Wouldn't want to add yet another collection of documentation notes to maintain.

Thanks for the idea though!
