### ISSUE TITLE
Port to react native

### ISSUE THREAD

**Issue by vinceprofeta** [jondavidjohn/payform#18]
Are there any plans to port this to React Native?

**Comment by jondavidjohn** [comment]
Haven't tried it myself, but I believe all the string formatting/validation helpers _should_ work fine.

You might have to wire up your own UI update logic, but all the card validation/formatting should work fine.

Let me know if it doesn't! 👌

**Comment by jondavidjohn** [comment]
Just saw that these are currently undocumented, but are part of the public API.

https://github.com/jondavidjohn/payform/blob/master/src/payform.coffee#L477-L518

For example, conceptually (untested)

```js
import { TextInput } from 'react-native'
import payform from 'payform'

class CreditCardInput extends Component {

  constructor() {
    super()
    this.state = { text: '' }
  }

  render() {
    return (
      <TextInput
        value={this.state.text}
        onChangeText={(text) => this.setState({text: payform.formatCardNumber(text)})}
      />
    )
  }
}
```

**Comment by jondavidjohn** [comment]
@yamartino might have some insight, [sounds like he's using it with react on the web](https://github.com/jondavidjohn/payform/pull/16#issuecomment-212581424)
