### ISSUE TITLE
Diners Club Formatting

### ISSUE THREAD

**Issue by vinceprofeta** [jondavidjohn/payform#19]
It seems the diners club formating is wrong. 

Stripe testing has `3056 9309 0259 04` as diners club sample test card
https://stripe.com/docs/testing

I believe the format should be: /(\d{1,4})(\d{1,4})?(\d{1,4})?(\d{1,2})?/

`{
      type: 'dinersclub'
      pattern: /^3[0689]/
      format: /(\d{1,4})(\d{1,6})?(\d{1,4})?/
      length: [14]
      cvcLength: [3]
      luhn: true
    }`

**Comment by jondavidjohn** [comment]
Would be open to a pull request if there is something here that needs fixing.

I know we're testing that diners club [here](https://github.com/jondavidjohn/payform/blob/master/test/validateCardNumber_spec.coffee#L64)

A good first start would be to just write a few failing tests to better illustrate the problem.

**Comment by mcarson-123** [comment]
Hi there. I'm wondering if this is the same issue as you were seeing @vinceprofeta 

When typing in the sample diner's club cc number to the form, when typing the second '5' the cursor shifts ahead of the 5 (Can see the result of typing the number `3056 9309 0259 04` exactly in order in the attached screen shot)

![screen shot 2017-01-20 at 3 50 10 pm](https://cloud.githubusercontent.com/assets/4604792/22169358/63c9ac5e-df28-11e6-8fa7-46135bd50462.png)

**Comment by jondavidjohn** [comment]
@mcarson-123 neat, thanks for the reproduction steps.  Have you experimented if this would be fixed by the updated regex that @vinceprofeta provided?

**Comment by jondavidjohn** [comment]
Alright, updated the format in the 1.2.1 release, thanks for the report @vinceprofeta.
