### ISSUE TITLE
Setting default value of field does not format properly

### ISSUE THREAD

**Issue by Starz26** [jondavidjohn/payform#23]
When either setting the value of the input when loading the DOM or setting the value of the input via javascript platform does not format the car number or the expiry based on the set values...

For example if I have this:

`<input value="4111111111111111" id="ccnum"/>`

When I initialize the field using

`$('#ccnum').payform('formatCardNumber');`

I would expect it to format the value of the input as if I had typed it in..

**Comment by jondavidjohn** [comment]
Makes sense, agree it would be a nice feature.  Though I'm not sure how common it is to store cc numbers in plain text on site and available to populate the field...

**Comment by Starz26** [comment]
It's mainly for this issue

1. User enters cc number
2. Clicks button that takes them to another page and cc number is passed along
3. They do xyz
4 click button to go back to cc form where previously entered number is passed back and st on the element

It would be nice to have it formatted again as setting the value does not seem to trigger anything

Due to framework simply hiding the payform is not possible between navigation

Make sense?

**Comment by Starz26** [comment]
So if on initialization of the field if it has a value and it is formatted that would fix the issue.

**Comment by Starz26** [comment]
It's mainly for navigation. They enter number. Go somewhere else to do xyz in payment form. Come back and component retendered with info they had already keyed in before navigation.  



--  
Eric Alexander

**Comment by jondavidjohn** [comment]
I see the utility.  I'd welcome a PR that implements it. 👍🏼

**Comment by Starz26** [comment]
I was able to do it using existing implementation. No need to update the library to support my request.

I am simply doing this when navigating back to the page

```
var inpEle = //getElement
if(inpEle && inpEle.value)
     inpEle.value = $.payform.formatCardNumber(inpEle.value);
```
