### ISSUE TITLE
Visa credit cards starting with 4917 fail validation

### ISSUE THREAD

**Issue by insidelabs** [jondavidjohn/payform#24]
We have an issue where valid visa credit card numbers starting with 4917 fail the regex validation. Is this a known issue?

**Comment by jondavidjohn** [comment]
Are you sure the card is valid?

![2017-04-21 at 11 51 am](https://cloud.githubusercontent.com/assets/401520/25287944/f5733100-2688-11e7-8a51-752dff0e59d4.png)

Looks like the test visa electron card works 👌
