### ISSUE TITLE
Maestro card entry stops short of last 2 digits

### ISSUE THREAD

**Issue by markolofsen** [jondavidjohn/payform#25]
**Can't input 6390 XXXX XXXX XXXX XX**

**Comment by jondavidjohn** [comment]
😬 Plz don't publish actual card numbers

Verified the problem is that the input stops before the last 2 numbers.

Thanks for the report 👍

**Comment by Stephs15** [comment]
Is there any progress on this issue?

**Comment by voronianski** [comment]
@markolofsen @Stephs15 any known workaround on this?

**Comment by voronianski** [comment]
this patch should fix the problem ☝️

**Comment by jondavidjohn** [comment]
Hi @markolofsen, is this no longer an issue with the published release?

**Comment by markolofsen** [comment]
@jondavidjohn don't know)
