### ISSUE TITLE
How to pre-fill the input value?

### ISSUE THREAD

**Issue by slavafomin** [jondavidjohn/payform#31]
Is there a way to pre-fill the input value and make the value properly formatted?

Thank you!

**Comment by slavafomin** [comment]
The workaround I use is to manually trigger the `input` event on the input field like this:

`inputElement.dispatchEvent(new CustomEvent('input', {}));`

**Comment by jondavidjohn** [comment]
This isn't a use case I've considered as most of the time you're not dealing with known card numbers (due to PCI compliance issues), glad you found a workaround!
