### ISSUE TITLE
Amex credit card validation failure

### ISSUE THREAD

**Issue by liamfl** [jondavidjohn/payform#33]
Hi,

My credit card service provider has given me some test card numbers and the Amex card number is failing validation... is this an error with payform?

The number is 34343434343434

Thanks
Liam

**Comment by jondavidjohn** [comment]
Amex card numbers are normally 16 digits, looks like you have a bad card number.

**Comment by liamfl** [comment]
Thanks for coming back to me so quickly - we’re the old ones 15 digit? There’s a lo of test cards on the web, and the pictures on the Amex website are all 15 digits.

Thanks
Liam

________________________________

**Comment by jondavidjohn** [comment]
The card you provided is 14

**Comment by liamfl** [comment]
That would explain it, and thanks for not calling me a * insert favoured swear word here *.

Love the library BTW.

Thanks
Liam

________________________________
