### ISSUE TITLE
Credit card numbers are displayed backwards when used in a RTL context

### ISSUE THREAD

**Issue by ddayguerrero** [jondavidjohn/payform#41]
## What is the issue?

Right-to-Left (RTL) directionality causes the credit card field formatter input value to be displayed backwards.

## How to reproduce the issue?
1- Create an instance of a Payform field formatter input (i.e. credit card number)

2- Use either HTML, CSS or JS to set the element's directionality to right-to-left.

<b>HTML:</b> `dir="rtl"`

<b>CSS:</b> `direction: rtl`

<b>JS:</b>

```JS
const ccInput = document.querySelector("#cc"); 
ccInput.dir = "rtl"; 
```
3- Begin typing a credit card number. For example, typing `1234 5678` will format into `5678 1234` instead of `1234 5678`.

## Discussion
A lot comes into play when talking about directionality (see W3C's article on [Handling RTL scripts](https://www.w3.org/TR/i18n-html-tech-bidi/) and the official [Unicode Bidirectional Algorithm](https://www.unicode.org/reports/tr9/) documentation). I will try to explain why the current state of the inputs do not display credit card numbers correctly:

1- Numbers in RTL scripts run left-to-right within the right-to-left flow and behave differently than words. In fact numbers are known to to have [weak directionality](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics#numbers).

2- <b> Given a native HTML input and with its directionality set to RTL: </b>

- Typing `12345678` will give us `12345678`. 
- Typing `1234 5678` will give us `5678 1234`. 
- Typing `CC 1234 5678` will give us `CC 1234 5678`.
- Typing `1234 5678 CC` will give us `CC 5678 1234`.

https://codepen.io/dramosrg/pen/MBWLXa

Because of this weak directionality, numbers are seen as part of the surrounding context. Without words to provide context of the input, elements cannot determine if the number being typed should be interpreted as a credit card number.

Since users are most likely to know that they will be typing credit card numbers, I believe that it is fair to assume that their credit card number should be displayed in a left-to-right fashion.

Therefore, typing `1234 5678` in a credit card field with a RTL flow should display `1234 5678`.

Stripe makes use of these conventions and displays credit card numbers [similarly](https://s.codepen.io/dramosrg/debug/vrQjjg/XxrVwavgWOGA).

**Comment by jondavidjohn** [comment]
Fixed @ `1.2.5`
