### ISSUE TITLE
Credit card number lengths

### ISSUE THREAD

**Issue by glebm** [jondavidjohn/payform#43]
Looks like many cards can have up to 19 digits:
https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blogs/2016/november/prepare-for-19-digit-credit-cards/

Number generator for validatons:
https://www.freeformatter.com/credit-card-number-generator-validator.html

The list here seems to be more up-to-date:
https://github.com/jessepollak/payment/blob/master/src/index.coffee

Also may have issues though, see e.g. https://github.com/jessepollak/payment/issues/98

**Comment by glebm** [comment]
The list here seems to be more up-to-date:

https://github.com/jessepollak/payment/blob/master/src/index.coffee

**Comment by jondavidjohn** [comment]
@glebm Is this resolved with #44 ?

**Comment by glebm** [comment]
I think so yeah
