### ISSUE TITLE
More maintainers?

### ISSUE THREAD

**Issue by arthurgouveia** [jondavidjohn/payform#49]
@jondavidjohn, I was wondering if you wouldn't appreciate splitting responsibilities a little more so that the community as a whole could benefit from the hard work you put on this repo.

I find that it is pretty hard nowadays to be lucky enough to maintain a full-time job + open source project such as this one. Maybe if we had more contributors with rights to merge PRs and do releases this could help you out.

The suggestion I have for now is @ddayguerrero, who's working with me on implementing this, but highly responsible for the hands on process.

What do you think?

**Comment by jondavidjohn** [comment]
Oh for sure, @ddayguerrero has been doing an awesome job.  I'll try to document some of the release processes in the next few days and add him.  Sounds like y'all are using this library, far more than I am these days. 👍

**Comment by jondavidjohn** [comment]
@ddayguerrero No, I'm sorry I've let it slip , thanks for the poke.

I just quickly wrote up the release process here: https://github.com/jondavidjohn/payform/blob/develop/CONTRIBUTING.md#release-process

I'll be adding your commit access and npm publishing rights shortly, and I'll let you take care of the next release if you're comfortable with that 🤘

**Comment by jondavidjohn** [comment]
@ddayguerrero What is your npm username?

Also before you actual do the npm publish of the release this first time, I'd like to double check everything if you don't mind, you can just ping me in this issue when you think you're all set.

**Comment by ddayguerrero** [comment]
No worries! 🎉

My npm username is: ddayguerrero
I'll go over the process over the next few days and make sure everything is clear. We should definitely go over it together for the first time!

**Comment by ddayguerrero** [comment]
@jondavidjohn I'm planning on releasing 1.2.6 soon. Would you be available to walk me through the `git flow` process? This is all new to me. Certain steps are implicit and I'm not sure if I'm on the right path.

Starting with the latest Payform's `develop` branch, I executed `$> git flow init` in order to proceed with `$> git flow release start 1.x.x`

I am prompted with the following:

```
$> git flow init

Which branch should be used for bringing forth production releases?
   - develop
   - master
```

I'm assuming the answer is `develop`? 😅I rather be certain instead of pushing unexpected changes.

**Comment by jondavidjohn** [comment]
We just use the default branch names, you can skip the prompts with `git flow init -d`

I'll add that to the docs 👍

**Comment by jondavidjohn** [comment]
@ddayguerrero 👌 Sounds good to me.

Just follow all the steps as outlined in the release documentation, *except for the npm publish step*.

Once you've pushed the new tag to GitHub I'll take a quick look and give you the ✅ to publish if everything looks good, we can always revert on the git side if anything goes sideways. 👍

**Comment by ddayguerrero** [comment]
Already done, just need a ✅ for the NPM publish! 😊

**Comment by jondavidjohn** [comment]
@ddayguerrero All looks good, publish away 👍 

Good job 🎉  and thanks for the help 💪

**Comment by jondavidjohn** [comment]
Looks like it's published, 👌 closing this issue.
